import type { Question } from "./types";

/**
 * Banco genérico da Prova do Espelho.
 * São perguntas amplas de ofício (não do conteúdo do PDI), usadas apenas para
 * definir em que ponto da jornada o viajante começa.
 */
export const DIAGNOSTIC_QUESTIONS: Question[] = [
  {
    id: "diag-01",
    region: "vale",
    materialId: "",
    axis: "formal",
    number: 1,
    difficulty: "light",
    xp: 20,
    type: "multiple_choice",
    prompt: "Em uma composição, o que mais ajuda a guiar o olho de quem vê?",
    options: [
      "Hierarquia visual entre os elementos",
      "Usar o máximo de cores possível",
      "Preencher todo o espaço disponível",
      "Aplicar sombras em tudo",
    ],
    answerIndex: 0,
    answerText: "Hierarquia visual entre os elementos",
    explanation: "Contraste, escala e espaço criam ordem de leitura antes de qualquer ornamento.",
  },
  {
    id: "diag-02",
    region: "vale",
    materialId: "",
    axis: "formal",
    number: 2,
    difficulty: "light",
    xp: 20,
    type: "true_false",
    prompt: "Espaço em branco (respiro) é desperdício de área no layout.",
    options: ["Verdadeiro", "Falso"],
    answerIndex: 1,
    answerText: "Falso",
    explanation: "O respiro é elemento ativo: agrupa, separa e dá ritmo à leitura.",
  },
  {
    id: "diag-03",
    region: "vale",
    materialId: "",
    axis: "figma",
    number: 3,
    difficulty: "medium",
    xp: 20,
    type: "multiple_choice",
    prompt: "Qual é o principal ganho de trabalhar com componentes reutilizáveis?",
    options: [
      "Consistência e mudanças propagadas em um só lugar",
      "Arquivos com menos páginas",
      "Exportar imagens mais rápido",
      "Evitar o uso de grids",
    ],
    answerIndex: 0,
    answerText: "Consistência e mudanças propagadas em um só lugar",
    explanation: "Componentes reduzem retrabalho e mantêm a linguagem visual coerente.",
  },
  {
    id: "diag-04",
    region: "vale",
    materialId: "",
    axis: "figma",
    number: 4,
    difficulty: "medium",
    xp: 20,
    type: "multiple_choice",
    prompt: "Ao entregar uma tela para desenvolvimento, o mais importante é:",
    options: [
      "Documentar estados, espaçamentos e comportamento",
      "Enviar apenas a imagem final em alta",
      "Escolher fontes decorativas",
      "Deixar tudo em um único quadro",
    ],
    answerIndex: 0,
    answerText: "Documentar estados, espaçamentos e comportamento",
    explanation: "A entrega é uma especificação, não só uma imagem bonita.",
  },
  {
    id: "diag-05",
    region: "vale",
    materialId: "",
    axis: "strategy",
    number: 5,
    difficulty: "medium",
    xp: 20,
    type: "multiple_choice",
    prompt: "Um briefing chega vago. Qual é o primeiro movimento?",
    options: [
      "Alinhar objetivo, público e critério de sucesso",
      "Começar a desenhar para ganhar tempo",
      "Escolher a paleta de cores",
      "Pedir mais prazo antes de conversar",
    ],
    answerIndex: 0,
    answerText: "Alinhar objetivo, público e critério de sucesso",
    explanation: "Sem problema definido, qualquer solução parece aceitável e nenhuma é defensável.",
  },
  {
    id: "diag-06",
    region: "vale",
    materialId: "",
    axis: "strategy",
    number: 6,
    difficulty: "advanced",
    xp: 20,
    type: "true_false",
    prompt: "Uma decisão de design fica mais forte quando é ligada a um objetivo do negócio.",
    options: ["Verdadeiro", "Falso"],
    answerIndex: 0,
    answerText: "Verdadeiro",
    explanation: "Argumento ligado a objetivo e evidência sustenta a decisão em qualquer mesa.",
  },
  {
    id: "diag-07",
    region: "vale",
    materialId: "",
    axis: "ai",
    number: 7,
    difficulty: "medium",
    xp: 20,
    type: "multiple_choice",
    prompt: "O que mais melhora o resultado ao usar IA generativa no trabalho criativo?",
    options: [
      "Contexto claro, referência e iteração do pedido",
      "Escrever o pedido mais curto possível",
      "Aceitar o primeiro resultado",
      "Evitar revisar a saída",
    ],
    answerIndex: 0,
    answerText: "Contexto claro, referência e iteração do pedido",
    explanation: "IA responde ao contexto: refinar o pedido vale mais do que repetir a geração.",
  },
  {
    id: "diag-08",
    region: "vale",
    materialId: "",
    axis: "ai",
    number: 8,
    difficulty: "advanced",
    xp: 20,
    type: "true_false",
    prompt: "Conteúdo gerado por IA pode ser publicado sem revisão humana de qualidade e direitos.",
    options: ["Verdadeiro", "Falso"],
    answerIndex: 1,
    answerText: "Falso",
    explanation: "A revisão humana responde por precisão, tom, direitos de uso e risco de marca.",
  },
  {
    id: "diag-09",
    region: "vale",
    materialId: "",
    axis: "image",
    number: 9,
    difficulty: "light",
    xp: 20,
    type: "multiple_choice",
    prompt: "Para impressão em alta qualidade, o mais adequado é:",
    options: [
      "Arquivo vetorial ou raster em alta resolução, em CMYK",
      "Captura de tela em 72 dpi",
      "JPG salvo em qualidade mínima",
      "GIF com poucas cores",
    ],
    answerIndex: 0,
    answerText: "Arquivo vetorial ou raster em alta resolução, em CMYK",
    explanation: "Resolução e espaço de cor corretos evitam perda visível na produção.",
  },
  {
    id: "diag-10",
    region: "vale",
    materialId: "",
    axis: "creative",
    number: 10,
    difficulty: "medium",
    xp: 20,
    type: "multiple_choice",
    prompt: "Qual prática mais amplia repertório criativo ao longo do tempo?",
    options: [
      "Coletar, estudar e criticar referências com regularidade",
      "Olhar só o trabalho dos concorrentes diretos",
      "Repetir a mesma solução que já funcionou",
      "Evitar áreas fora do design",
    ],
    answerIndex: 0,
    answerText: "Coletar, estudar e criticar referências com regularidade",
    explanation: "Repertório é construído por acúmulo deliberado e variado, não por acaso.",
  },
  {
    id: "diag-11",
    region: "vale",
    materialId: "",
    axis: "accessibility",
    number: 11,
    difficulty: "medium",
    xp: 20,
    type: "multiple_choice",
    prompt: "Um texto cinza-claro sobre fundo branco falha principalmente em:",
    options: [
      "Contraste suficiente para leitura",
      "Alinhamento de grid",
      "Escolha de família tipográfica",
      "Tamanho do arquivo",
    ],
    answerIndex: 0,
    answerText: "Contraste suficiente para leitura",
    explanation: "Contraste insuficiente exclui parte das pessoas antes de qualquer estética.",
  },
  {
    id: "diag-12",
    region: "vale",
    materialId: "",
    axis: "accessibility",
    number: 12,
    difficulty: "advanced",
    xp: 20,
    type: "true_false",
    prompt: "Usar apenas cor para indicar erro em um formulário é uma solução acessível.",
    options: ["Verdadeiro", "Falso"],
    answerIndex: 1,
    answerText: "Falso",
    explanation: "Cor precisa vir acompanhada de texto ou ícone para não depender da visão de cor.",
  },
];

/** Sugere o ponto de partida da jornada a partir do desempenho geral. */
export function suggestStartingStage(
  correct: number,
  total: number,
): {
  stage: string;
  advice: string;
} {
  const rate = total ? correct / total : 0;
  if (rate >= 0.8)
    return {
      stage: "Trilha avançada",
      advice:
        "Sua base está firme. Comece pelos materiais de estratégia, sistemas e maestria — as regiões mais altas do mapa.",
    };
  if (rate >= 0.5)
    return {
      stage: "Trilha intermediária",
      advice:
        "Você domina o essencial. Comece pelos materiais de ferramenta e processo antes de subir para o planalto.",
    };
  return {
    stage: "Trilha inicial",
    advice:
      "Comece pelo Vale: fundamentos formais, ferramentas e repertório abrem todas as trilhas seguintes.",
  };
}
